"""empty message

Revision ID: 35fa806b5d3b
Revises: 7329a1bb4ef5
Create Date: 2019-03-28 00:00:15.081076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35fa806b5d3b'
down_revision = '7329a1bb4ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bulb', 'is_forbid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulb', sa.Column('is_forbid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
