"""empty message

Revision ID: 55facd87384e
Revises: 
Create Date: 2019-03-26 15:05:30.441582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55facd87384e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('info', sa.String(length=100), nullable=True),
    sa.Column('ele_use', sa.Integer(), nullable=True),
    sa.Column('open_num', sa.Integer(), nullable=True),
    sa.Column('close_num', sa.Integer(), nullable=True),
    sa.Column('is_demage', sa.Integer(), nullable=True),
    sa.Column('is_forbid', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_bulb_create_time'), 'bulb', ['create_time'], unique=False)
    op.create_index(op.f('ix_bulb_update_time'), 'bulb', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bulb_update_time'), table_name='bulb')
    op.drop_index(op.f('ix_bulb_create_time'), table_name='bulb')
    op.drop_table('bulb')
    # ### end Alembic commands ###
