"""empty message

Revision ID: 7329a1bb4ef5
Revises: 55facd87384e
Create Date: 2019-03-27 23:59:12.129496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7329a1bb4ef5'
down_revision = '55facd87384e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulb', sa.Column('open_state', sa.Integer(), nullable=True))
    op.add_column('bulb', sa.Column('state', sa.Integer(), nullable=True))
    op.add_column('bulb', sa.Column('use_num', sa.Integer(), nullable=True))
    op.add_column('bulb', sa.Column('use_time', sa.Integer(), nullable=True))
    op.drop_column('bulb', 'open_num')
    op.drop_column('bulb', 'is_demage')
    op.drop_column('bulb', 'close_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulb', sa.Column('close_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('bulb', sa.Column('is_demage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('bulb', sa.Column('open_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('bulb', 'use_time')
    op.drop_column('bulb', 'use_num')
    op.drop_column('bulb', 'state')
    op.drop_column('bulb', 'open_state')
    # ### end Alembic commands ###
