"""empty message

Revision ID: dfe8b6ce1e9b
Revises: 35fa806b5d3b
Create Date: 2019-03-28 00:05:37.480819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe8b6ce1e9b'
down_revision = '35fa806b5d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulb', sa.Column('location', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bulb', 'location')
    # ### end Alembic commands ###
